zv01/zv01/Models/Evento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace zv01.Models
{
    public class Evento
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public DateTimeOffset EventDate { get; set; }
        public string Categoria { get; set; }
        public string Description { get; set; }
        public string Place { get; set; }
        public int AforoActual { get; set; }
        public int AforoTotal { get; set; }
        public int ListaEspera { get; set; }
        public AppUser AppUser { get; set; }
        public EstadoEvento Estado { get; set; }
        public int Visitas { get; set; }
        public EventImg Imgs { get; set; }
        public bool EstaBorrado { get; set; }

    }
}

zv01/zv01/Controllers/EventImgsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using zv01.Data;
using zv01.Models;

namespace zv01.Controllers
{
    public class EventImgsController : Controller
    {
        private readonly AzureStorageConfig _storageConfig;
        private readonly ApplicationDbContext _context;
        private readonly IConfiguration _configuration;


        public EventImgsController(ApplicationDbContext context, IConfiguration Configuration, IOptions<AzureStorageConfig> storageConfig)
        {
            _storageConfig = storageConfig.Value;
            _context = context;
            _configuration = Configuration;


        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("UploadFiles")]
        public async Task<IActionResult> Post(List<IFormFile> files, [Bind("id,ImgUrl")] EventImg eventImg, [Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")] Evento evento, string time)
        {
            var uploadSuccess = false;

            foreach (var formFile in files)
            {
                if (formFile.Length <= 0)
                {
                    continue;
                }

                // NOTE: uncomment either OPTION A or OPTION B to use one approach over another

                // OPTION A: convert to byte array before upload
                //using (var ms = new MemoryStream())
                //{
                //    formFile.CopyTo(ms);
                //    var fileBytes = ms.ToArray();
                //    uploadSuccess = await UploadToBlob(formFile.FileName, fileBytes, null);

                //}

                // OPTION B: read directly from stream for blob upload      
                using (var stream = formFile.OpenReadStream())
                {

                    uploadSuccess = await UploadFileToStorage(stream, formFile.FileName, _storageConfig, eventImg, evento, time);
                }

            }

            if (uploadSuccess)
            {
                return RedirectToAction("Create", "Eventos");
            }
            else
            {
                return View("UploadError");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<bool> UploadFileToStorage(Stream fileStream, string fileName, AzureStorageConfig _storageConfig, [Bind("id,ImgUrl")] EventImg eventImg, [Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")] Evento evento, string time)
        {
            // Create storagecredentials object by reading the values from the configuration (appsettings.json)
            StorageCredentials storageCredentials = new StorageCredentials(_storageConfig.AccountName, _storageConfig.AccountKey);

            // Create cloudstorage account by passing the storagecredentials
            CloudStorageAccount storageAccount = new CloudStorageAccount(storageCredentials, true);

            // Create the blob client.
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

            // Get reference to the blob container by passing the name by reading the value from the configuration (appsettings.json)
            CloudBlobContainer container = blobClient.GetContainerReference(_storageConfig.EventImgContainer);

            // Get the reference to the block blob from the container
            CloudBlockBlob blockBlob = container.GetBlockBlobReference(fileName);

            // Upload the file
            await blockBlob.UploadFromStreamAsync(fileStream);

            var blobUrl = blockBlob.Uri.AbsoluteUri;
            var img = new EventImg
            {
                ImgUrl = blobUrl
            };

            _context.Add(img);
            await _context.SaveChangesAsync();

            DateTimeOffset eventodate = evento.EventDate;
            var timeSpanVal = time.ToString().Split(':').Select(x => Convert.ToInt32(x)).ToList();
            TimeSpan ts = new TimeSpan(timeSpanVal[0], timeSpanVal[1], 00);
            evento.EventDate = eventodate.Add(ts);
            evento.Estado = _context.EstadoEventos.Single(x => x.Id == 1);
            evento.Imgs = img;
            evento.AforoActual = 0;
            evento.Visitas = 0;

            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();
                
            }
            return await Task.FromResult(true);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        // GET: EventImgs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventImg = await _context.EventImg
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventImg == null)
            {
                return NotFound();
            }

            return View(eventImg);
        }

        // GET: EventImgs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EventImgs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ImgUrl")] EventImg eventImg)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventImg);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eventImg);
        }

        // GET: EventImgs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventImg = await _context.EventImg.FindAsync(id);
            if (eventImg == null)
            {
                return NotFound();
            }
            return View(eventImg);
        }

        // POST: EventImgs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImgUrl")] EventImg eventImg)
        {
            if (id != eventImg.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventImg);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventImgExists(eventImg.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventImg);
        }

        // GET: EventImgs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventImg = await _context.EventImg
                .FirstOrDefaultAsync(m => m.Id == id);
            if (eventImg == null)
            {
                return NotFound();
            }

            return View(eventImg);
        }

        // POST: EventImgs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventImg = await _context.EventImg.FindAsync(id);
            _context.EventImg.Remove(eventImg);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventImgExists(int id)
        {
            return _context.EventImg.Any(e => e.Id == id);
        }
    }
}

zv01/zv01/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using zv01.Data;
using zv01.Models;

namespace zv01.Controllers
{
    public class EventosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly AzureStorageConfig _config;


        public EventosController(ApplicationDbContext context, UserManager<AppUser> userManager, IOptions<AzureStorageConfig> config)
        {
            _context = context;
            _userManager = userManager;
            _config = config.Value;
        }

        // GET: Eventos
        public async Task<IActionResult> Index(AppUser appUser, int option)
        {
            return await Filter(option);

        }
        public async Task<IActionResult> ListadoEventos(AppUser appUser, int option)
        {
            return await Filter(option);

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }
            else if(!User.IsInRole("Administrador") && !User.IsInRole("Pica"))
            {
                evento.Visitas = evento.Visitas+1;
                _context.Evento.Update(evento);
                await _context.SaveChangesAsync();
            }

            return View(evento);

        }

        // GET: Eventos/Create
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")]string time, Evento evento)
        {
            
            DateTimeOffset eventodate = evento.EventDate;
            var timeSpanVal = time.ToString().Split(':').Select(x => Convert.ToInt32(x)).ToList();
            TimeSpan ts = new TimeSpan(timeSpanVal[0], timeSpanVal[1], 00);
            evento.EventDate = eventodate.Add(ts);
            evento.Estado = _context.EstadoEventos.Single(x => x.Id == 1);  
            

            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        //Registrarse a un evento



        // GET: Eventos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento.FindAsync(id);
            if (evento == null)
            {
                return NotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")]string time, Evento evento)
        {

            
            DateTimeOffset eventodate = evento.EventDate;
            var timeSpanVal = time.Split(':').Select(x => Convert.ToInt32(x)).Take(2).ToList();
            TimeSpan ts = new TimeSpan(timeSpanVal[0], timeSpanVal[1], 00);
            eventodate = eventodate.Add(ts);
            evento.EventDate = eventodate;

            if (id != evento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoExists(evento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evento = await _context.Evento.FindAsync(id);
            _context.Evento.Remove(evento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool EventoExists(int id)
        {
            return _context.Evento.Any(e => e.Id == id);
        }


        private async Task<IActionResult> Filter(int option)
        {
            if (option == 0)
            {
                List<Evento> eventos = await _context.Evento.Include(x=>x.Imgs).ToListAsync();
                return View(eventos);
            }

            else if (option == 1)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.Visitas).ToListAsync());

            }
            else if (option == 2)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.EventDate).ToListAsync());
            }

            else if (option == 3)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.AforoActual).ToListAsync());
            }
            else if (option == 4)
            {
                return View(await _context.Evento.OrderBy(evento => evento.AforoActual).ToListAsync());
            }
            else
            {
                return View();
            }
        }
    }
}

zv01/zv01/Views/Eventos/AgregarEvento.cshtml
@model zv01.Models.Evento

@{
    ViewData["Title"] = "AgregarEvento";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>AgregarEvento</h2>

<h4>Evento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AgregarEvento">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" class="form-control" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AforoActual" class="control-label"></label>
                <input asp-for="AforoActual" class="form-control" />
                <span asp-validation-for="AforoActual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AforoTotal" class="control-label"></label>
                <input asp-for="AforoTotal" class="form-control" />
                <span asp-validation-for="AforoTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ListaEspera" class="control-label"></label>
                <input asp-for="ListaEspera" class="form-control" />
                <span asp-validation-for="ListaEspera" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Visitas" class="control-label"></label>
                <input asp-for="Visitas" class="form-control" />
                <span asp-validation-for="Visitas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

zv01/zv01/Views/Eventos/Create.cshtml
@model zv01.Models.Evento
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Create</h2>
<h4>Evento</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <div id="file-preview-zone">
            @*ESTE ID ES LO DEL JS DE ABAJO DEL TODO. AUN FALTA CAMBIAR CSS PARA ALTURA Y ANCHURA DE FOTO*@
            @*Imagen a cambiar*@
            <img class="img-responsive" @*src="~/images/Create/portada.jpg" *@ />
        </div>
        <form method="post" enctype="multipart/form-data" asp-controller="EventImgs" asp-action="Post">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload one file using this form:</p>
                    <input id="file-upload" type="file" name="files" acept="image/*" />
                </div>
            </div>
            <h4>&nbsp;</h4>
            <div>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Upload" />
                    </div>
                </div>
            </div>

            <h4>&nbsp;</h4>
    </div>


    <div class="col-md-4">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="EventName" class="control-label"></label>
            <input asp-for="EventName" class="form-control" />
            <span asp-validation-for="EventName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EventDate" class="control-label"></label>
            <input asp-for="EventDate" id="date" class="form-control" type="date" />
            <input name="time" class="form-control" type="time" />
            <span asp-validation-for="EventDate" class="text-danger"></span>
        </div>
        @*<div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" id="date" class="form-control" type="date"/>
                <input asp-for="EventDate" id="time" class="form-control" type="time" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>*@
        <div class="form-group">
            <label asp-for="Place" class="control-label"></label>
            <input asp-for="Place" class="form-control" />
            <span asp-validation-for="Place" class="text-danger"></span>
        </div>
  
        <div class="form-group">
            <label asp-for="AforoTotal" class="control-label"></label>
            <input asp-for="AforoTotal" class="form-control" />
            <span asp-validation-for="AforoTotal" class="text-danger"></span>
        </div>
 
   
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <textarea asp-for="Description" class="form-control" rows="7" cols="40"></textarea>
            @*<input asp-for="Description" class="form-control" />*@
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>
    </form>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    function readFile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                var filePreview = document.createElement('img');
                filePreview.id = 'file-preview';
                //e.target.result contents the base64 data from the image uploaded
                filePreview.src = e.target.result;
                console.log(e.target.result);

                var previewZone = document.getElementById('file-preview-zone');
                previewZone.appendChild(filePreview);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    var fileUpload = document.getElementById('file-upload');
    fileUpload.onchange = function (e) {
        readFile(e.srcElement);
    }

</script>

zv01/zv01/Views/Eventos/Delete.cshtml
@model zv01.Models.Evento

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AforoActual)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AforoActual)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AforoTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AforoTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Visitas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Visitas)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

zv01/zv01/Views/Eventos/Details.cshtml
@model zv01.Models.Evento

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Evento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AforoActual)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AforoActual)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AforoTotal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AforoTotal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Visitas)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Visitas)
        </dd>
    </dl>
</div>
<div>
    @*<button asp-controller="Reservas" asp-action="registerEvent" asp-route-id="@Model.Id">Evento</button>*@
    @{
        if (User.Identity.IsAuthenticated)
        {
            <a type="button" class="btn btn-primary" class="btn" asp-controller="Reservas" asp-action="registerEvent" asp-route-id="@Model.Id">Registrar Evento</a>
        }
      
    }
    @{
        if (User.IsInRole("Administrador"))
        {
            <a type="button" class="btn btn-primary" class="btn" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        }
    }
    <a type="button" class="btn btn-primary" asp-action="Index">Back to List</a>
</div>

zv01/zv01/Views/Eventos/Edit.cshtml
@model zv01.Models.Evento

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


<h4>Evento</h4>
<h4>&nbsp;</h4>
<hr />
<div class="row">
    <div class="col-md-8">      
        <h4>&nbsp;</h4>
    </div>
    <div class="col-md-4">
        <form asp-action="Post" asp-controller="Eventos">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="EventName" class="control-label"></label>
                <input asp-for="EventName" class="form-control" />
                <span asp-validation-for="EventName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDate" class="control-label"></label>
                <input asp-for="EventDate" id="date" class="form-control" type="date" />
                <input asp-for="EventDate" id="time" name="time" class="form-control" type="time" />
                <span asp-validation-for="EventDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Place" class="control-label"></label>
                <input asp-for="Place" class="form-control" />
                <span asp-validation-for="Place" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AforoActual" class="control-label"></label>
                <input asp-for="AforoActual" class="form-control" />
                <span asp-validation-for="AforoActual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AforoTotal" class="control-label"></label>
                <input asp-for="AforoTotal" class="form-control" />
                <span asp-validation-for="AforoTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Visitas" class="control-label"></label>
                <input asp-for="Visitas" class="form-control" />
                <span asp-validation-for="Visitas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea type="text" asp-for="Description" class="form-control" rows="7" cols="40"></textarea>
                @*<input asp-for="Description" class="form-control" />*@
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Upload" method="post" asp-controller="Eventos" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    function readFile(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                var filePreview = document.createElement('img');
                filePreview.id = 'file-preview';
                //e.target.result contents the base64 data from the image uploaded
                filePreview.src = e.target.result;
                console.log(e.target.result);

                var previewZone = document.getElementById('file-preview-zone');
                previewZone.appendChild(filePreview);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    var fileUpload = document.getElementById('file-upload');
    fileUpload.onchange = function (e) {
        readFile(e.srcElement);
    }

</script>