zv01/zv01/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using zv01.Data;
using zv01.Models;

namespace zv01.Controllers
{
    public class EventosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly AzureStorageConfig _config;


        public EventosController(ApplicationDbContext context, UserManager<AppUser> userManager, IOptions<AzureStorageConfig> config)
        {
            _context = context;
            _userManager = userManager;
            _config = config.Value;
        }

        // GET: Eventos
        public async Task<IActionResult> Index(AppUser appUser, int option)
        {
            return await Filter(option);

        }
        public async Task<IActionResult> ListadoEventos(AppUser appUser, int option)
        {
            return await Filter(option);

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }
            else if(!User.IsInRole("Administrador") && !User.IsInRole("Pica"))
            {
                evento.Visitas = evento.Visitas+1;
                _context.Evento.Update(evento);
                await _context.SaveChangesAsync();
            }

            return View(evento);

        }

        // GET: Eventos/Create
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")]string time, Evento evento)
        {
            
            DateTimeOffset eventodate = evento.EventDate;
            var timeSpanVal = time.ToString().Split(':').Select(x => Convert.ToInt32(x)).ToList();
            TimeSpan ts = new TimeSpan(timeSpanVal[0], timeSpanVal[1], 00);
            evento.EventDate = eventodate.Add(ts);
            evento.Estado = _context.EstadoEventos.Single(x => x.Id == 1);  
            

            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        //Registrarse a un evento



        // GET: Eventos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento.FindAsync(id);
            if (evento == null)
            {
                return NotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")]string time, Evento evento)
        {

            
            DateTimeOffset eventodate = evento.EventDate;
            var timeSpanVal = time.Split(':').Select(x => Convert.ToInt32(x)).Take(2).ToList();
            TimeSpan ts = new TimeSpan(timeSpanVal[0], timeSpanVal[1], 00);
            eventodate = eventodate.Add(ts);
            evento.EventDate = eventodate;

            if (id != evento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoExists(evento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evento = await _context.Evento.FindAsync(id);
            _context.Evento.Remove(evento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool EventoExists(int id)
        {
            return _context.Evento.Any(e => e.Id == id);
        }


        private async Task<IActionResult> Filter(int option)
        {
            if (option == 0)
            {
                List<Evento> eventos = await _context.Evento.Include(x=>x.Imgs).ToListAsync();
                return View(eventos);
            }

            else if (option == 1)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.Visitas).ToListAsync());

            }
            else if (option == 2)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.EventDate).ToListAsync());
            }

            else if (option == 3)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.AforoActual).ToListAsync());
            }
            else if (option == 4)
            {
                return View(await _context.Evento.OrderBy(evento => evento.AforoActual).ToListAsync());
            }
            else
            {
                return View();
            }
        }
    }
}

zv01/zv01/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using zv01.Data;
using zv01.Models;


namespace zv01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
            
        }

        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }


        //hola
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

zv01/zv01/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

zv01/zv01/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

zv01/zv01/Views/Home/Index.cshtml
@model IEnumerable<zv01.Models.Evento>
@inject zv01.Services.Zv01Services Zv01Services
@{
    ViewData["Title"] = "Lista de eventos";
}

<header class="v-header container">
    <div class="fullscreen-video-wrap">
        <video src="~/images/videos/motionplace.mp4" autoplay="" muted="" loop=""></video>
    </div>
    <div class="header-overlay"></div>
    <div class="header-content text-md-center">

        <h1>Encuentra tu evento</h1>
        <h4>&nbsp;</h4>
        <form>
            <input type="text" />
            <div class="after"></div>
            <input type="submit" />
        </form>
    </div>
</header>
<section class="section section-a">
    <div class="container">
        <h2>Mas que una Experiencia</h2>
        <p>E-vent es una aplicación web que permite organizar eventos culturales , deportivos , empresariales con la finalidad de crear de tu evento una experiencia con facilidades de publicitarse. </p>
    </div>
</section>

<section class="section section-b">
    <div class="container">
        <h2>Exito garantizado</h2>
        <p>Ofrece a los visitantes a tu sitio web una experiencia de registro sencillo , que permite la automatización de eventos como una lista de espera para las personas que desean ingresar a un evento y no se registran a tiempo , de esta forma tienen la oportunidad de poder ir a sus eventos favoritos en caso de que se liberen espacios.</p>
    </div>
</section>

<div data-vide-bg="motionplace">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>
        <br />
        <br />
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="~/images/Bussines.jpg" alt="ASP.NET" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <h2>Bussines</h2>
                    <p>

                        <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                            Ver eventos
                        </a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/Cocina.jpg" alt="Visual Studio" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <h2>Cocina</h2>
                    <p>

                        <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                            Ver eventos
                        </a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/Eventos.jpg" alt="Microsoft Azure" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <h2>Cultural</h2>
                    <p>

                        <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                            Ver eventos
                        </a>
                    </p>
                </div>
            </div>
            <div class="item">
                <img src="~/images/Musica.jpg" alt="Microsoft Azure" class="img-responsive" />
                <div class="carousel-caption" role="option">
                    <h2>Musica</h2>
                    <p>
                        <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409"> Ver eventos </a>
                    </p>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    @*Comienza las 3 views de eventos*@

    <div class="row">
        <div class="col-md-4">
            <h2> El mas visto </h2>
            <div class="wrap">
                @{
                    Evento maxVis = Zv01Services.EventoMaxVis();
                }
                <div class="tile">
                    <a asp-controller="Eventos" asp-action="Details" asp-route-id="@maxVis.Id">
                        <img src="@maxVis.Imgs.ImgUrl" />
                        <div class="text">
                            <h1 class="animate-text">@maxVis.EventName</h1>
                            <h2 class="animate-text">@maxVis.EventDate</h2>
                            <p class="animate-text">@maxVis.Description</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4">

            <h2> El mas Solicitado </h2>
            <div class="wrap">
                @{
                    Evento maxAfo = Zv01Services.EventoMaxAfo();
                }
                <div class="tile">
                    <a asp-controller="Eventos" asp-action="Details" asp-route-id="@maxAfo.Id">
                        <img src="@maxAfo.Imgs.ImgUrl" asp-controller="Eventos" asp-action="Details" asp-route-id="@maxAfo.Id" />
                        <div class="text">
                            <h1 class="animate-text">@maxAfo.EventName</h1>
                            <h2 class="animate-text">@maxAfo.EventDate</h2>
                            <p class="animate-text">@maxAfo.Description</p>

                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-10">
            <h2> El mas nuevo </h2>
            <div class="wrap">
                @{
                    Evento maxTime = Zv01Services.EventoLast();
                }
                <div class="tile">
                    <a asp-controller="Eventos" asp-action="Details" asp-route-id="@maxTime.Id">
                        <img src="@maxTime.Imgs.ImgUrl" />
                        <div class="text">
                            <h1 class="animate-text">@maxTime.EventName</h1>
                            <h2 class="animate-text">@maxTime.EventDate</h2>
                            <p class="animate-text">@maxTime.Description</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/Searchan.js"></script>