zv01/zv01/Controllers/AppRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using zv01.Data;
using zv01.Models;

namespace zv01.Controllers
{
    public class AppRolesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;

        public AppRolesController(ApplicationDbContext context, UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            

        }
       
        public async Task<IActionResult> SearchUser(string searchString, int role)
        {
            AppUser user = await _userManager.FindByEmailAsync(searchString);
            var userInRole = _context.UserRoles.FirstOrDefault(x => x.UserId == user.Id);
            

            if (user != null && userInRole == null)
            {
                if (role == 1)
                {
                    await _userManager.AddToRoleAsync(user, "Administrador");
                    await _context.SaveChangesAsync();
                }
                else if (role == 2)
                {
                    await _userManager.AddToRoleAsync(user, "Pica");
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index", "Home");

            }
            else
            {
                return RedirectToAction("Create", "Eventos");
                //View(await user.ToListAsync());
            }

        }

        public async Task<IActionResult> DeleteUser(string searchString)
        {
            AppUser user = await _userManager.FindByEmailAsync(searchString);

            if (user != null)
            {
                await _userManager.RemoveFromRoleAsync(user, "Administrador");
                await _context.SaveChangesAsync();
                return RedirectToAction("Create", "Reservas");
                //Create();

            }
            else
            {
                return RedirectToAction("Create", "Eventos");
                //View(await user.ToListAsync());
            }
        }

        // GET: AppRoles
        public async Task<IActionResult> Index()
        {
            return View(await _context.AppRole.ToListAsync());
        }

        // GET: AppRoles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appRole = await _context.AppRole
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appRole == null)
            {
                return NotFound();
            }

            return View(appRole);
        }

        // GET: AppRoles/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Creates()
        {
            return View();
        }
        public IActionResult AdminPanel()
        {
            return View();
        }
        // POST: AppRoles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Description,CreationDate,Id,Name,NormalizedName,ConcurrencyStamp")] AppRole appRole)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appRole);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appRole);
        }

        // GET: AppRoles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appRole = await _context.AppRole.FindAsync(id);
            if (appRole == null)
            {
                return NotFound();
            }
            return View(appRole);
        }

        // POST: AppRoles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Description,CreationDate,Id,Name,NormalizedName,ConcurrencyStamp")] AppRole appRole)
        {
            if (id != appRole.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appRole);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppRoleExists(appRole.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appRole);
        }
        //
        // GET: AppRoles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appRole = await _context.AppRole
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appRole == null)
            {
                return NotFound();
            }

            return View(appRole);
        }
        
        // POST: AppRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var appRole = await _context.AppRole.FindAsync(id);
            _context.AppRole.Remove(appRole);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppRoleExists(string id)
        {
            return _context.AppRole.Any(e => e.Id == id);
        }
    }
}

zv01/zv01/Controllers/EventosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using zv01.Data;
using zv01.Models;

namespace zv01.Controllers
{
    public class EventosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        private readonly AzureStorageConfig _config;


        public EventosController(ApplicationDbContext context, UserManager<AppUser> userManager, IOptions<AzureStorageConfig> config)
        {
            _context = context;
            _userManager = userManager;
            _config = config.Value;
        }

        // GET: Eventos
        public async Task<IActionResult> Index(AppUser appUser, int option)
        {
            return await Filter(option);

        }
        public async Task<IActionResult> ListadoEventos(AppUser appUser, int option)
        {
            return await Filter(option);

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }
            else if(!User.IsInRole("Administrador") && !User.IsInRole("Pica"))
            {
                evento.Visitas = evento.Visitas+1;
                _context.Evento.Update(evento);
                await _context.SaveChangesAsync();
            }

            return View(evento);

        }

        // GET: Eventos/Create
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")]string time, Evento evento)
        {
            
            DateTimeOffset eventodate = evento.EventDate;
            var timeSpanVal = time.ToString().Split(':').Select(x => Convert.ToInt32(x)).ToList();
            TimeSpan ts = new TimeSpan(timeSpanVal[0], timeSpanVal[1], 00);
            evento.EventDate = eventodate.Add(ts);
            evento.Estado = _context.EstadoEventos.Single(x => x.Id == 1);  
            

            if (ModelState.IsValid)
            {
                _context.Add(evento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        //Registrarse a un evento



        // GET: Eventos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento.FindAsync(id);
            if (evento == null)
            {
                return NotFound();
            }
            return View(evento);
        }

        // POST: Eventos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,EventName,EventDate,Description,Place,AforoActual,AforoTotal,Visitas")]string time, Evento evento)
        {

            
            DateTimeOffset eventodate = evento.EventDate;
            var timeSpanVal = time.Split(':').Select(x => Convert.ToInt32(x)).Take(2).ToList();
            TimeSpan ts = new TimeSpan(timeSpanVal[0], timeSpanVal[1], 00);
            eventodate = eventodate.Add(ts);
            evento.EventDate = eventodate;

            if (id != evento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventoExists(evento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(evento);
        }

        // GET: Eventos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Evento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        // POST: Eventos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evento = await _context.Evento.FindAsync(id);
            _context.Evento.Remove(evento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool EventoExists(int id)
        {
            return _context.Evento.Any(e => e.Id == id);
        }


        private async Task<IActionResult> Filter(int option)
        {
            if (option == 0)
            {
                List<Evento> eventos = await _context.Evento.Include(x=>x.Imgs).ToListAsync();
                return View(eventos);
            }

            else if (option == 1)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.Visitas).ToListAsync());

            }
            else if (option == 2)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.EventDate).ToListAsync());
            }

            else if (option == 3)
            {
                return View(await _context.Evento.OrderByDescending(evento => evento.AforoActual).ToListAsync());
            }
            else if (option == 4)
            {
                return View(await _context.Evento.OrderBy(evento => evento.AforoActual).ToListAsync());
            }
            else
            {
                return View();
            }
        }
    }
}

zv01/zv01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Eventia</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/Master.css" />
        <link rel="stylesheet" href="~/css/adminpnl.css" />
        <link rel="stylesheet" href="~/css/events.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/Eventia.png" /></a>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">E-Vent</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Eventos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Eventos" asp-action="Index">Eventos</a></li>
                            @{
                                if (User.Identity.IsAuthenticated)
                                {

                                    <li><a asp-area="" asp-controller="Reservas" asp-action="ReservasUsuario">Mis Reservas</a></li>
                                }

                            }
                        </ul>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - zv01</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

zv01/zv01/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - zv01</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/Master.css" />
        <link rel="stylesheet" href="~/css/adminpnl.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">zv01</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Eventos <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a asp-area="" asp-controller="Eventos" asp-action="Index">Eventos</a></li>
                            <li><a asp-area="" asp-controller="Eventos" asp-action="Create">Crear eventos</a></li>
                        </ul>
                    </li>

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    <div class="area"></div><nav class="main-menuss navbar-left">
                                <ul>
                                    <li>
                                        <br /><br /><br /><br />
                                    </li>


                                    <li>
                                        <a asp-controller="Eventos" asp-action="ListadoEventos"> <i class=" fa fa-calendar fa-2x"></i> <span class="nav-text">  Eventos </span></a>
                                        <ul class="dropdown-menu-right">
                                            <li class="has-subnav">
                                                <a asp-controller="Eventos" asp-action="Create"> <i class="fa fa-pencil fa-2x"></i> <span class="nav-text"> Crear Eventos </span></a>

                                            </li>
                                            <li class="has-subnav">
                                                <a asp-controller="Eventos" asp-action="ListadoEventos"> <i class="fa fa-home fa-2x"></i> <span class="nav-text"> Editar Eventos </span></a>

                                            </li>
                                        </ul>
                                    </li>
                                    <li class="has-subnav">
                                        <a asp-controller="AppRoles" asp-action="Index"> <i class=" fa fa-check-square fa-2x"></i> <span class="nav-text">  Roles de usuarios </span></a>

                                    </li>
                                    <li class="has-subnav">
                                        <a asp-controller="Reservas" asp-action="ReservasUsuario"> <i class="fa fa-heart fa-2x"></i> <span class="nav-text">  Mis Reservas </span></a>

                                    </li>                       
                                    <li class="has-subnav">
                                        <a asp-controller="Reservas" asp-action="ReservasPorEvento"> <i class="fa fa-phone fa-2x"></i> <span class="nav-text">  Reservas por Evento </span></a>

                                    </li>
                                </ul>
        @*<li class="has-subnav">
                    <a href="#">
                        <i class="fa fa-list fa-2x"></i>
                        <span class="nav-text">
                            Forms
                        </span>
                    </a>

                </li>
                <li class="has-subnav">
                    <a href="#">
                        <i class="fa fa-folder-open fa-2x"></i>
                        <span class="nav-text">
                            Pages
                        </span>
                    </a>

                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-bar-chart-o fa-2x"></i>
                        <span class="nav-text">
                            Graphs and Statistics
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-font fa-2x"></i>
                        <span class="nav-text">
                            Quotes
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-table fa-2x"></i>
                        <span class="nav-text">
                            Tables
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-map-marker fa-2x"></i>
                        <span class="nav-text">
                            Maps
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-info fa-2x"></i>
                        <span class="nav-text">
                            Documentation
                        </span>
                    </a>
                </li>


            <ul class="logout">
                <li>
                    <a href="#">
                        <i class="fa fa-power-off fa-2x"></i>
                        <span class="nav-text">
                            Logout
                        </span>
                    </a>
                </li>
            </ul>*@
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - zv01</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>